### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by IndieCoderMM** [PrantoshB/Ruby-To-Do-List#2]
Your todo app has a nice UI and all CRUD features work perfectly. ✅

I have one suggestion to improve the overall UX of the app. 

You did a great job validating inputs on the menu. 

But users can type anything as indexes for deleting and updating tasks.

- It would be great to validate every input with available options. I think it would make a better UX for your app.

**Comment by PrantoshB** [comment]
### Hello @IndieCoderMM, 

![](https://media.giphy.com/media/uWlpPGquhGZNFzY90z/giphy.gif)
I am so glad that you have tried my app and suggested changes. 🫱🏼‍🫲🏽
I have worked on that. And in this version:
- When the user enters invalid input as indexes while updating and deleting the tasks, it'll show an error.

Please let me know if I can improve anything else.

### Cheers 🍻

**Comment by IndieCoderMM** [comment]
Thanks for considering my suggestion. You're the best 👍👍🥂

Now that I can't find a way to break your app so I'm just gonna add empty items to my todo-list and start working on them. 😁
